//: [Previous](@previous)
//: # Полезные ссылки
//: ### [hackingwithswift](https://www.hackingwithswift.com/quick-start/swiftui/how-to-synchronize-animations-from-one-view-to-another-with-matchedgeometryeffect)
//: ### [learnmetoo](https://learnmetoo.ru/blog/uncat/matched-geometry-effects)
//: ### [appcoda](https://www.appcoda.com/learnswiftui/swiftui-matchedgeometry.html)
//: ### [swiftui-lab_1](https://swiftui-lab.com/matchedgeometryeffect-part1/)
//: ### [swiftui-lab_2](https://swiftui-lab.com/matchedgeometryeffect-part2/)
//: ### [augmentedcode](https://augmentedcode.io/2023/05/15/getting-started-with-matched-geometry-effect-in-swiftui/)
//: ### [designcode](https://designcode.io/swiftui-handbook-matched-geometry-effect/)
//: ### [apptractor](https://apptractor.ru/develop/sozdaem-animirovannye-perehody-s-pomoschyu-matched-geometry-effect-v-swiftui.html)
//: ### [fatbobman](https://fatbobman.com/en/posts/exploring-swiftui-property-wrappers-3/)
//: ### [holyswift](https://holyswift.app/tag/matchedgeometryeffect/)
//: ### [reddit](https://www.reddit.com/r/SwiftUI/comments/rfrjs2/crazy_simple_matchedgeometryeffect_trick_that/)
//: ### [iankeen](https://iankeen.tech/2020/07/03/cross-view-animations-with-matchedgeometryeffect/index.html)
