name: Telegram scheduled messages

on:
  schedule:
    # 11:00 MSK → 08:00 UTC (понедельник, вторник, пятница)
    - cron: '0 8 * * 1'
    - cron: '0 8 * * 2'
    - cron: '0 8 * * 5'
    # 16:50 MSK → 13:50 UTC (вторник)
    - cron: '50 13 * * 2'

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID:  ${{ secrets.CHAT_ID }}
    steps:
      - name: Send Telegram scheduled message
        shell: bash
        env:
          TZ: Europe/Moscow
        run: |
          # Заставим date использовать московское время
          export TZ

          DAY=$(date +%u)       # 1=понедельник … 7=воскресенье
          TIME=$(date +%H:%M)   # локальное (MSK) время

          echo "DEBUG: сейчас по Москве ${DAY} ${TIME}"

          case "${DAY} ${TIME}" in
            "5 11:"*)  # пятница в любой минуте часа 11
              MESSAGE="📅 Привет! Сегодня пятница, нужно определиться с докладчиками на iOS Weekly."
              ;;
            "1 11:"*)  # понедельник 11:00–11:59
              MESSAGE="📅 Привет! Завтра iOS Weekly. Докладчики, не забудьте про свои доклады!"
              ;;
            "2 11:"*)  # вторник 11:00–11:59
              MESSAGE="📅 Привет! Сегодня iOS Weekly в 17:00!"
              ;;
            "2 16:5"*) # вторник 16:50–16:59
              MESSAGE="📅 Увидимся через 10 минут!"
              ;;
            *)
              echo "Не время для отправки (сейчас ${DAY} ${TIME}), выходим."
              exit 0
              ;;
          esac

          # отправляем сообщение
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="$MESSAGE"
