name: Telegram scheduled messages

on:
  schedule:
    # Понедельник 11:00 MSK → UTC 08:00
    - cron: '0 8 * * 1'
    # Вторник 11:00 MSK → UTC 08:00
    - cron: '0 8 * * 2'
    # Вторник 16:50 MSK → UTC 13:50
    - cron: '50 13 * * 2'
    # Пятница 11:00 MSK → UTC 08:00
    - cron: '0 8 * * 5'

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram scheduled message
        shell: bash
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
          TZ:        Europe/Moscow
        run: |
          # получаем московский день недели (1–понедельник … 7–воскресенье) и время HH:MM
          DAY=$(date +%u)
          TIME=$(date +%H:%M)

          case "${DAY} ${TIME}" in
            # Пятница 11:00
            "5 11:00")
              MESSAGE="📅 Привет! Сегодня пятница, нужно определиться с докладчиками на iOS Weekly."
              ;;
            # Понедельник 11:00
            "1 11:00")
              MESSAGE="📅 Привет! Завтра iOS Weekly. Докладчики, не забудьте про свои доклады!"
              ;;
            # Вторник 11:00
            "2 11:00")
              MESSAGE="📅 Привет! Сегодня iOS Weekly в 17:00!"
              ;;
            # Вторник 16:50
            "2 16:50")
              MESSAGE="📅 Увидимся через 10 минут!"
              ;;
            *)
              echo "Не время для отправки (сейчас ${DAY} ${TIME}), выходим."
              exit 0
              ;;
          esac

          # шлём в Telegram
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="$MESSAGE"
