name: Telegram scheduled messages

on:
  schedule:
    # 11:00 MSK → 08:00 UTC (понедельник, вторник, пятница)
    - cron: '0 8 * * 1'
    - cron: '0 8 * * 2'
    - cron: '0 8 * * 5'
    # 16:50 MSK → 13:50 UTC (вторник)
    - cron: '50 13 * * 2'

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID:  ${{ secrets.CHAT_ID }}
    steps:
      - name: Send Telegram scheduled message
        shell: bash
        env:
          TZ: Europe/Moscow
        run: |
          # убедимся, что date будет в московской зоне
          export TZ

          # номер дня недели (1=понедельник…7=воскресенье) и локальное время HH:MM
          DAY=$(date +%u)
          TIME=$(date +%H:%M)

          echo "DEBUG: сейчас по Москве ${DAY} ${TIME}"

          case "${DAY} ${TIME}" in
            # Пятница в течение часа 11:xx
            5 11:*)
              MESSAGE="📅 Привет! Сегодня пятница, нужно определиться с докладчиками на iOS Weekly."
              ;;
            # Понедельник в течение часа 11:xx
            1 11:*)
              MESSAGE="📅 Привет! Завтра iOS Weekly. Докладчики, не забудьте про свои доклады!"
              ;;
            # Вторник в течение часа 11:xx
            2 11:*)
              MESSAGE="📅 Привет! Сегодня iOS Weekly в 17:00!"
              ;;
            # Вторник в течение минут 50–59 (16:50–16:59)
            2 16:5*)
              MESSAGE="📅 Увидимся в 17:00!"
              ;;
            *)
              echo "Не время для отправки (сейчас ${DAY} ${TIME}), выходим."
              exit 0
              ;;
          esac

          # отправка сообщения
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="$MESSAGE"
