name: iOS Weekly — 10-minute reminder

on:
  schedule:
    - cron: '50 13 * * 2' # Вторник 13:50 UTC = 16:50 MSK

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send 10-minute reminder
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.CHAT_ID }}" \
            -d text "📅 Увидимся через 10 минут!"
